### ISSUE TITLE
Look into simple(r) task notations

### ISSUE THREAD

**Issue by rikardg** [rikardg/bygg#212]
Sometimes one just wants to do something really simple. One way could be to declare these as just a task name and the command as the value, like Poe the Poet does: https://github.com/nat-n/poethepoet .

```toml
[tool.poe.tasks]
test         = "pytest --cov=my_app"                         # a simple command task
serve.script = "my_app.service:run(debug=True)"              # python script based task
tunnel.shell = "ssh -N -L 0.0.0.0:8080:$PROD:8080 $PROD &"   # (posix) shell based task
```
